import { Experience } from "@/types";

export const experiences: Experience[] = [
  {
    id: "1",
    role: "Freelance Full-Stack Web Developer",
    company: "Independent / Self-Employed",
    type: "Freelance",
    period: "Jan 2024 - Present",
    location: "Remote",
    bullets: [
      "Architected and deployed EasyExamSolution, a subscription-based EdTech SaaS platform serving 1,800+ registered users and 159+ active subscribers.",
      "Engineered a high-performance Supabase PostgreSQL architecture with advanced indexing and query optimization, enabling sub-2-second retrieval across 67,000+ exam questions.",
      "Built TaskMatrix, an enterprise task management platform for software houses with Firebase Authentication, role-based access control, real-time Firestore synchronization, and agile workflow tracking.",
      "Developed PakWaqt, a Next.js utility application using SSR and SSG, real-time API integrations, responsive UI, and advanced SEO optimization.",
      "Delivered 5+ client projects including SMMWorldBooster frontend redesigns, responsive business websites, landing pages, and custom web applications.",
      "Worked directly with clients on requirements, UI implementation, API integration, deployment, bug fixing, and iterative improvements.",
      "Built responsive e-commerce interfaces with product catalogs, filtering, product management, authentication, and checkout-focused user experiences for client-style projects.",
      "Developed custom business dashboards and admin interfaces with reusable React components, REST API integrations, authentication, and role-based access control.",
      "Maintained 95%+ on-time delivery across freelance projects through direct client communication and structured development workflows.",
    ],
  },
  {
    id: "2",
    role: "Full-Stack Developer",
    company: "MediConnect",
    type: "Contract",
    period: "Oct 2024 - Dec 2024",
    location: "Remote",
    bullets: [
      "Developed healthcare appointment platform processing 1,500+ monthly appointments",
      "Integrated Daily.co API for HIPAA-compliant video consultations",
      "Built SMS/WhatsApp reminder system using Twilio, achieving 99.2% delivery rate",
      "Implemented multi-language support (English + Urdu) with RTL layout",
      "Achieved 91 Lighthouse performance score with Next.js SSR",
    ],
  },
  {
    id: "3",
    role: "Frontend Developer",
    company: "InventoryIQ",
    type: "Freelance",
    period: "Jul 2024 - Sep 2024",
    location: "Remote",
    bullets: [
      "Built AI-powered inventory system for retailers with 87% demand forecast accuracy",
      "Implemented offline-first architecture using Service Workers and IndexedDB",
      "Designed camera-based barcode scanning with html5-qrcode",
      "Created Python microservice (FastAPI) for time-series forecasting",
      "Reduced client stockout incidents by 40% through automated reordering",
    ],
  },
  {
    id: "4",
    role: "Full-Stack Developer",
    company: "EduStream",
    type: "Personal Project",
    period: "Apr 2024 - Jun 2024",
    location: "Remote",
    bullets: [
      "Architected live learning platform supporting 1,200+ concurrent viewers",
      "Integrated Mux API for low-latency live streaming with automatic recording",
      "Built real-time interactive quiz system processing 500+ responses per minute",
      "Implemented AI study planner using collaborative filtering",
      "Designed subscription tier system with Stripe + JazzCash integration",
    ],
  },
  {
    id: "5",
    role: "Frontend Developer",
    company: "CryptoWatch",
    type: "Personal Project",
    period: "Feb 2024 - Mar 2024",
    location: "Remote",
    bullets: [
      "Developed real-time crypto dashboard tracking 500+ cryptocurrencies",
      "Integrated CoinGecko API and Binance WebSocket for sub-1-second price updates",
      "Built TradingView chart integration with RSI, MACD, and Bollinger Bands",
      "Implemented news sentiment analysis using Python VADER",
      "Achieved 93 Lighthouse performance score with dark-mode-first UI",
    ],
  },
];