import { Project } from "@/types";

export const projects: Project[] = [
  {
    id: "1",
    title: "EasyExamSolution",
    slug: "easyexamsolution",
    description: "Subscription-based SaaS with 1,800+ users and 159 subscribers. 67,000+ questions database.",
    category: "EdTech",
    tags: ["SaaS", "EdTech", "Subscription"],
    techStack: ["React", "Node.js", "Firebase", "Stripe"],
    liveUrl: "https://easyexamsolution.online",
    githubUrl: "https://github.com/TeamBarry",
    image: "/images/easyexam.jpg",
    metrics: [
      { label: "Users", value: "1,800+" },
      { label: "Subscribers", value: "159" },
      { label: "Questions", value: "67,000+" },
    ],
  },
  {
    id: "2",
    title: "Live Crypto Dashboard",
    slug: "crypto-dashboard",
    description: "Real-time cryptocurrency tracking with WebSocket, live charts, and portfolio analytics.",
    category: "Fintech",
    tags: ["Fintech", "Real-time", "WebSocket"],
    techStack: ["React 18", "TypeScript", "Redux Toolkit", "Node.js", "WebSocket"],
    liveUrl: "https://live-crypto-dashboard-alpha.vercel.app/",
    githubUrl: "https://github.com/TeamBarry/Live-Crypto-DashBoard",
    image: "/images/crypto.jpg",
    metrics: [
      { label: "Coins Tracked", value: "500+" },
      { label: "Update Latency", value: "<1s" },
      { label: "Lighthouse", value: "93" },
    ],
  },
  {
    id: "3",
    title: "CraftAIWorld",
    slug: "craftaiworld",
    description: "AI-powered design platform with 124+ countries, 92K+ patterns, 5,600+ artists.",
    category: "AI/ML",
    tags: ["AI", "Design", "Global"],
    techStack: ["Next.js", "TypeScript", "OpenAI API", "Supabase"],
    liveUrl: "https://craftaiworld.com",
    githubUrl: "https://github.com/TeamBarry",
    image: "/images/craftai.jpg",
    metrics: [
      { label: "Countries", value: "124+" },
      { label: "Patterns", value: "92K+" },
      { label: "Artists", value: "5,600+" },
    ],
  },
  {
    id: "4",
    title: "TaskFlow Pro",
    slug: "taskflow-pro",
    description: "SaaS project management platform with real-time collaboration and kanban boards.",
    category: "SaaS",
    tags: ["SaaS", "Project Management", "Real-time"],
    techStack: ["Next.js 15", "TypeScript", "Socket.io", "Supabase", "Zustand"],
    liveUrl: "https://taskflow-pro.vercel.app",
    githubUrl: "https://github.com/TeamBarry",
    image: "/images/taskflow.jpg",
    metrics: [
      { label: "Beta Users", value: "200+" },
      { label: "Concurrent", value: "500+" },
      { label: "API Latency", value: "<100ms" },
    ],
  },
  {
    id: "5",
    title: "MediConnect",
    slug: "mediconnect",
    description: "HIPAA-compliant healthcare appointment platform for Pakistani clinics.",
    category: "Healthcare",
    tags: ["Healthcare", "Telemedicine", "Pakistan"],
    techStack: ["Next.js 15", "TypeScript", "Supabase", "Twilio", "Daily.co"],
    liveUrl: "https://mediconnect-pk.vercel.app",
    githubUrl: "https://github.com/TeamBarry",
    image: "/images/mediconnect.jpg",
    metrics: [
      { label: "Monthly Appts", value: "1,500+" },
      { label: "SMS Delivery", value: "99.2%" },
      { label: "No-show Reduction", value: "35%" },
    ],
  },
   {
    id: "6",
    title: "TaskMatrix",
    slug: "taskmatrix",
    description:
      "Enterprise-grade task management system for software houses with developer and manager identity management, real-time task synchronization, and agile workflow tracking.",
    category: "SaaS",
    tags: ["SaaS", "Task Management", "Real-time", "Agile"],
    techStack: ["React", "Firebase Auth", "Firestore", "Real-time Sync"],
    liveUrl: "https://taskmatrix.teambarry.blog",
    githubUrl: "https://github.com/zubair-zafar/taskmatrix",
    image: "/images/taskmatrix.jpg",
    metrics: [
      { label: "Authentication", value: "Firebase" },
      { label: "Sync", value: "Real-time" },
      { label: "Workflow", value: "Agile" },
    ],
  },
  {
    id: "7",
    title: "PakWaqt",
    slug: "pakwaqt",
    description:
      "Localized utility web application built with Next.js SSR and SSG, featuring real-time API integrations, mobile-first responsive UI, and advanced SEO optimization.",
    category: "Web Application",
    tags: ["Next.js", "SSR", "SSG", "SEO"],
    techStack: ["Next.js", "SSR", "SSG", "REST APIs"],
    liveUrl: "https://pakwaqt.teambarry.blog",
    githubUrl: "https://github.com/TeamBarry",
    image: "/images/pakwaqt.jpg",
    metrics: [
      { label: "Rendering", value: "SSR + SSG" },
      { label: "SEO", value: "Optimized" },
      { label: "UI", value: "Mobile-first" },
    ],
  },
  {
    id: "8",
    title: "Shopping Website with Virtual Try-On",
    slug: "shopping-virtual-try-on",
    description:
      "Full-stack e-commerce platform featuring a unique Virtual Try-On experience, secure checkout flow, and complete product management system.",
    category: "E-Commerce",
    tags: ["E-Commerce", "Virtual Try-On", "Full-Stack"],
    techStack: ["React", "Node.js", "MongoDB"],
    liveUrl: "https://teambarry.github.io/vite-react-deploy/",
    githubUrl:
      "https://github.com/TeamBarry/vite-react-deploy",
    image: "/images/shopping.jpg",
    metrics: [
      { label: "Platform", value: "E-Commerce" },
      { label: "Feature", value: "Virtual Try-On" },
      { label: "Backend", value: "Node.js" },
    ],
  },
];